server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: task-service-route
          uri: lb://task-service
          predicates:
            - Path=/api/tasks, /api/tasks/**
          filters:
            - AuthenticationFilter
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users, /api/users/**
          filters:
            - AuthenticationFilter
        - id: ai-service
          uri: http://ai-service:8000
          predicates:
            - Path=/api/ai/**
          filters:
            - AuthenticationFilter
application:
  security:
    jwt:
      secret-key: ${TOKEN_SECRET_KEY}
      expiration-time: ${TOKEN_EXPIRATION_TIME}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG